### PR TITLE
chore: Update and refactor docs of getting_started.md

### PR DESCRIPTION
**Pull request by ritwikraha**
- Massive restructure of the getting started docs
- More diagrams
- Explaining each step of the process
- Adding a section about custom extractors before using available extractors
- Experimented by adding a header image (we can remove if unnecessary)
- New and restructured "Next Steps" section

### CODE REVIEW

**Comment by ritwikraha** [comment]
cc: @diptanu what do you think?

**Comment by diptanu** [comment]
@ritwikraha Left you some comments on the page itself! Looking good.

**Comment by ritwikraha** [comment]
> @ritwikraha Left you some comments on the page itself! Looking good.

Thanks I will resolve these

**Comment by ritwikraha** [comment]
Most of the comments are resolved now!

**Comment by ritwikraha** [comment]
update: this is now in a mergable state

**Pull request merged**
