### PR TITLE
Added CONTRIBUTION.md file

### LINKED ISSUE #960: Missing Contribution.md file
There is a need to add a contribution.md file. So that anyone who wants to contribute have an idea of what steps to follow for contribution.
I want to work on this issue. Please assign me this task.

### PR DESCRIPTION
**Pull request by yaarAdarsh**
Please review this PR where I added contribution.md file with necessary details in it.
Fixes #960

### CODE REVIEW

**Comment by yaarAdarsh** [comment]
@adithyaakrishna please review my PR / merge it.

**Comment by yaarAdarsh** [comment]
@diptanu please review my PR

**Comment by diptanu** [comment]
@yaarAdarsh This needs a lot more change, won't be able to get to it for another week at least. Might be better if we do it.

**Comment by yaarAdarsh** [comment]
okay

**Pull request closed without merging**
